### ISSUE TITLE
File permissions in the opa_library tar

### ISSUE THREAD

**Issue by leefernandes** [ticketmaster/rules_opa#16]
With @rules_opa:v0.2.0 want to use the output from `opa_library` in `container_image.deps` but when the opa image runs it can't read any files due to a lack of read permission.  I inspected the file contents of the generated tar and they're all `0600`.  Current opa containers don't run as root user.

Would it be possible to give files being added to the tar `0644` permission so they can be read by opa?

**Comment by ffortier** [comment]
Hello,

I probably need to update the README to refer to the release page but 0.2.0 is not the latest version. Could you try again with the latest version [v0.4.0](https://github.com/ticketmaster/rules_opa/releases/tag/v0.4.0)?

Also, just to be sure are you signing your bundle using the `signing_key` attribute on `opa_library`?

**Comment by leefernandes** [comment]
It looks like your changes in 0.5.0 resolved issues I was having with file perms and the rootless opa images.  thanks 🙏
