### ISSUE TITLE
Can you unblock my ISPs IPs?

### ISSUE THREAD

**Issue by imduffy15** [ticketmaster/rules_opa#27]
Hey folks!

I've tried to contact ticketmaster support on this issue but had no luck, figured this might be a better path to getting it in front of technical folks.

For some reason, ticketmaster blocks all my my ISPs IP ranges, it looks like this isn't the first time this has occurred, see https://www.mail-archive.com/nanog@nanog.org/msg92653.html where they found resolution by:

> What i ended up doing was spamming any technical and C-level execs i could find on LinkedIN and finally found one that 
was able to help. That was years ago though so i dont have a contact there anymore.

A handful of customers from my ISP have complained along with the ISP itself:

https://twitter.com/DanielBrierton/status/1573363617193684992
https://twitter.com/mneylon/status/1520498014460252160
https://twitter.com/blacknight/status/1518881278245974016
https://twitter.com/blacknight/status/1518635173428051969

I tried the twitter approach myself but was unsuccessful too:

https://twitter.com/imduffy15/status/1734309610310312000

Maybe you can assist?

AS39122 specifically those registered under "Blacknight Broadband Customers":

185.152.72.0/22
185.206.192.0/22
185.209.164.0/22
194.36.58.0/23
194.36.64.0/23

and v6:

2a01:a8::/32
2a01:ad::/32

Thanks!

Ian.

**Comment by imduffy15** [comment]
![unnamed (1)](https://github.com/ticketmaster/rules_opa/assets/1243435/6741e5c0-09d9-44ba-a211-ca3f43eafcd7)

**Comment by imduffy15** [comment]
Hey @ffortier just retested I'm afraid the issue still persists. 

You can see the 403 in chrome dev tools here and a failure to load the seating map:
<img width="1686" alt="Screenshot 2023-12-13 at 19 13 48" src="https://github.com/ticketmaster/rules_opa/assets/1243435/5f5f8fd3-ef64-446b-958b-5194fd2ae774">

**Comment by ffortier** [comment]
I've informed the people in charge of this.

**Comment by imduffy15** [comment]
Awesome! Thank you.

**Comment by emilstahl** [comment]
@ffortier Maybe you can help us too?

Our corporate office IPs are blocked. I have raised multiple tickets and Twitter DM’s without any luck. I was even (falsly) told that I’m permanently banned due to breach of ToS…

AS48854 – team.blue Denmark A/S, yes we are a hosting provider and I understand that you might have blocked us for being hosting/datacenter/VPN/anon, but as I tried to explain 185.25.142.0/24 is dedicated for our own internal corporate/business office use.
