### ISSUE TITLE
Q: does this support bazel coverage? 

### ISSUE THREAD

**Issue by loeffel-io** [ticketmaster/rules_opa#50]
Thanks

**Comment by ffortier** [comment]
Not yet, but I can add this to my todo list.

**Comment by loeffel-io** [comment]
Would be amazing 🙏

**Comment by ffortier** [comment]
@loeffel-io when you get a chance, can you try this https://github.com/ticketmaster/rules_opa/pull/59

**Comment by loeffel-io** [comment]
💯 🙏  

it will take some time until i can test it but i will let you know! great job
